FROM ubuntu:latest
WORKDIR /home/webrtc
RUN apt update \
 && apt install -y \
    python3 \
    git \
    curl \
    openjdk-17-jdk \
    lsb-release \
    sudo \
    file \
    xz-utils \
    nano \
    tree \
    wget \
    binutils
 
